name: Deploy to GitHub Pages

on:
  push:
    paths:
      - "./gh-deployment-workflow/index.html"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

  env:
    BASE_URL: https://rahullulla.github.io/devops-labs/gh-deployment-workflow/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./" # Points to the folder containing index.html

      - name: Deployment Success Message
        run: echo "Deployment to GitHub Pages was successful!"

      - name: Output deployment URL
        run: echo "The website is deployed at ${{ env.BASE_URL }}" # Using environment variables
