name: Deploy to GitHub Pages

on:
  push:
    paths:
      - "./index.html"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

  env:
    BASE_URL: https://rahullulla.github.io/gh-deployment-workflow

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch to deploy your built site to
          FOLDER: . # The folder containing your static files or build output

      - name: Deployment Success Message
        run: echo "Deployment to GitHub Pages was successful!"
